### PR TITLE
Reorganize launch files

### PR DESCRIPTION
**Pull request by wuphilipp**
This should be pulled with this PR from the blue_core repository. 
https://github.com/berkeleyopenarms/blue_core/pull/76

### CODE REVIEW

**Comment by wuphilipp** [comment]
This should cause no functional changes but reorganizes the structure a bit. Not sure if this is the final form we want but I wanted to start a discussion about it.

**Comment by brentyi** [comment]
This looks much cleaner!

Some thoughts (I can help with implementing):
- Maybe remove rviz? I think it'd be nice if these mirrored the functionality of the blue_bringup launch files as much as possible
- It'd be nice if the file naming/directory structure matched the convention we use in [blue_bringup](https://github.com/berkeleyopenarms/blue_core/tree/master/blue_bringup/launch)
- Is there a reason we start controllers in the pickup world but not the empty one?
- Comments would be nice

**Comment by wuphilipp** [comment]
Yes! I removed rviz and tried to match the convention in blue_bringup as much as possible. Comments are also added!

The controllers are launched because otherwise, the right arm drops. Once it makes a collision with the table the mimic joints bug out. For some reason, only the right arm has this behavior. Let me know if you find any good ways of fixing that!

**Comment by brentyi** [comment]
Looks great! Ready to merge as soon as the conflicts are sorted out.

One question -- how do you feel about disabling the mimic joint Gazebo plugin, or making it so the plugin needs to be explicitly enabled? It's really hard to use Gazebo with the plugin enabled because of all the restarting needed; I've been manually disabling it.

**Review by brentyi — APPROVED** [review]

**Comment by brentyi** [comment]
Just kidding, approval retracted -- I can't get `full.launch` to work. Gazebo opens, but when I run rviz things seem broken. Also, a z component was added and the robot's now floating in the air?

**Comment by wuphilipp** [comment]
The z component is to account for the addition of the gravity dependency 
 (https://github.com/berkeleyopenarms/blue_core/pull/76) and was meant to help address this issue.
https://github.com/berkeleyopenarms/blue_core/issues/74

My bad on breaking rviz. It should be fixed now.

**Pull request merged**
